spring.application.name=CounsellorPortal

# DataSource properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/jrtp29
spring.datasource.username=root
spring.datasource.password=Subbu@001

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
